### ISSUE TITLE
Using OP_RETURN as lib has no detection for hexlike strings.

### ISSUE THREAD

**Issue by Biersteker** [coinspark/php-OP_RETURN#1]
if (preg_match('/^([0-9A-Fa-f]{2})*$/', $metadata))
		$metadata=pack('H*', $metadata); // convert from hex if it looks like hex
	
Should be placed in OP_RETURN.php instead off in the sendopreturnscript. (Changed it in my fork).

**Comment by gidgreen** [comment]
Thanks but I'm afraid I don't agree. At the PHP library level I think it makes sense not to have hexadecimal detection, because of the risk of ambiguous strings being misinterpreted. A PHP programmer can always use pack('H*', ...) before passing data to the function. The reason there's support for hex input on the command line is that it can be difficult to use non-ASCII strings as command-line parameters. Again though, thanks for the suggestion.

**Comment by Biersteker** [comment]
Then might I suggest maybe something like:
if($metadata_len>OP_RETURN_MAX_BYTES && $metadata_len<OP_RETURN_MAX_BYTES*2 )
if (preg_match('/^([0-9A-Fa-f]{2})$/', $metadata) {
//stuff
} else {
return array('error' => 'Metadata has '.$metadata_len.' bytes but is limited to '.OP_RETURN_MAX_BYTES.' (see OP_RETURN_MAX_BYTES)');
}
}
That if metadata exceeds max bytes, it still is checked for being hex already.? (bit pseudo code above).

**Comment by gidgreen** [comment]
Thanks again, but from my experience I don't think it's a good idea to have this kind of dual-behavior programmer interface. If anything, it should be an explicit parameter specifying the input format, or a separate function.
